// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutionData.proto

package ca.pollutionData;

/**
 * Protobuf type {@code pollutionData.GetMonthIndexResponse}
 */
public  final class GetMonthIndexResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pollutionData.GetMonthIndexResponse)
    GetMonthIndexResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetMonthIndexResponse.newBuilder() to construct.
  private GetMonthIndexResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetMonthIndexResponse() {
    monthIndex_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetMonthIndexResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            monthIndex_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.pollutionData.PollutionDataProto.internal_static_pollutionData_GetMonthIndexResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.pollutionData.PollutionDataProto.internal_static_pollutionData_GetMonthIndexResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.pollutionData.GetMonthIndexResponse.class, ca.pollutionData.GetMonthIndexResponse.Builder.class);
  }

  public static final int MONTH_INDEX_FIELD_NUMBER = 1;
  private int monthIndex_;
  /**
   * <code>int32 month_index = 1;</code>
   */
  public int getMonthIndex() {
    return monthIndex_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (monthIndex_ != 0) {
      output.writeInt32(1, monthIndex_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (monthIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, monthIndex_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.pollutionData.GetMonthIndexResponse)) {
      return super.equals(obj);
    }
    ca.pollutionData.GetMonthIndexResponse other = (ca.pollutionData.GetMonthIndexResponse) obj;

    boolean result = true;
    result = result && (getMonthIndex()
        == other.getMonthIndex());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MONTH_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getMonthIndex();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.pollutionData.GetMonthIndexResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.pollutionData.GetMonthIndexResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.pollutionData.GetMonthIndexResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.pollutionData.GetMonthIndexResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.pollutionData.GetMonthIndexResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.pollutionData.GetMonthIndexResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.pollutionData.GetMonthIndexResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.pollutionData.GetMonthIndexResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.pollutionData.GetMonthIndexResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.pollutionData.GetMonthIndexResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.pollutionData.GetMonthIndexResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.pollutionData.GetMonthIndexResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.pollutionData.GetMonthIndexResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pollutionData.GetMonthIndexResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pollutionData.GetMonthIndexResponse)
      ca.pollutionData.GetMonthIndexResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.pollutionData.PollutionDataProto.internal_static_pollutionData_GetMonthIndexResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.pollutionData.PollutionDataProto.internal_static_pollutionData_GetMonthIndexResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.pollutionData.GetMonthIndexResponse.class, ca.pollutionData.GetMonthIndexResponse.Builder.class);
    }

    // Construct using ca.pollutionData.GetMonthIndexResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      monthIndex_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.pollutionData.PollutionDataProto.internal_static_pollutionData_GetMonthIndexResponse_descriptor;
    }

    @java.lang.Override
    public ca.pollutionData.GetMonthIndexResponse getDefaultInstanceForType() {
      return ca.pollutionData.GetMonthIndexResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ca.pollutionData.GetMonthIndexResponse build() {
      ca.pollutionData.GetMonthIndexResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.pollutionData.GetMonthIndexResponse buildPartial() {
      ca.pollutionData.GetMonthIndexResponse result = new ca.pollutionData.GetMonthIndexResponse(this);
      result.monthIndex_ = monthIndex_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.pollutionData.GetMonthIndexResponse) {
        return mergeFrom((ca.pollutionData.GetMonthIndexResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.pollutionData.GetMonthIndexResponse other) {
      if (other == ca.pollutionData.GetMonthIndexResponse.getDefaultInstance()) return this;
      if (other.getMonthIndex() != 0) {
        setMonthIndex(other.getMonthIndex());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.pollutionData.GetMonthIndexResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.pollutionData.GetMonthIndexResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int monthIndex_ ;
    /**
     * <code>int32 month_index = 1;</code>
     */
    public int getMonthIndex() {
      return monthIndex_;
    }
    /**
     * <code>int32 month_index = 1;</code>
     */
    public Builder setMonthIndex(int value) {
      
      monthIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 month_index = 1;</code>
     */
    public Builder clearMonthIndex() {
      
      monthIndex_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pollutionData.GetMonthIndexResponse)
  }

  // @@protoc_insertion_point(class_scope:pollutionData.GetMonthIndexResponse)
  private static final ca.pollutionData.GetMonthIndexResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.pollutionData.GetMonthIndexResponse();
  }

  public static ca.pollutionData.GetMonthIndexResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetMonthIndexResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetMonthIndexResponse>() {
    @java.lang.Override
    public GetMonthIndexResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetMonthIndexResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetMonthIndexResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetMonthIndexResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.pollutionData.GetMonthIndexResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

