// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutionData.proto

package ca.pollutionData;

public interface GetMonthIndexRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pollutionData.GetMonthIndexRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string month_name = 1;</code>
   */
  java.lang.String getMonthName();
  /**
   * <code>string month_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getMonthNameBytes();
}
