// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutionData.proto

package ca.pollutionData;

public interface GetMonthIndexResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pollutionData.GetMonthIndexResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 month_index = 1;</code>
   */
  int getMonthIndex();
}
