// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutionData.proto

package ca.pollutionData;

public interface GetReadingsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pollutionData.GetReadingsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 dublin_air_pollution = 1;</code>
   */
  int getDublinAirPollution();

  /**
   * <code>int32 dublin_water_pollution = 2;</code>
   */
  int getDublinWaterPollution();

  /**
   * <code>int32 cork_air_pollution = 3;</code>
   */
  int getCorkAirPollution();

  /**
   * <code>int32 cork_water_pollution = 4;</code>
   */
  int getCorkWaterPollution();
}
