// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutionData.proto

package ca.pollutionData;

/**
 * Protobuf type {@code pollutionData.GetReadingsResponse}
 */
public  final class GetReadingsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pollutionData.GetReadingsResponse)
    GetReadingsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetReadingsResponse.newBuilder() to construct.
  private GetReadingsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetReadingsResponse() {
    dublinAirPollution_ = 0;
    dublinWaterPollution_ = 0;
    corkAirPollution_ = 0;
    corkWaterPollution_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetReadingsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            dublinAirPollution_ = input.readInt32();
            break;
          }
          case 16: {

            dublinWaterPollution_ = input.readInt32();
            break;
          }
          case 24: {

            corkAirPollution_ = input.readInt32();
            break;
          }
          case 32: {

            corkWaterPollution_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.pollutionData.PollutionDataProto.internal_static_pollutionData_GetReadingsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.pollutionData.PollutionDataProto.internal_static_pollutionData_GetReadingsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.pollutionData.GetReadingsResponse.class, ca.pollutionData.GetReadingsResponse.Builder.class);
  }

  public static final int DUBLIN_AIR_POLLUTION_FIELD_NUMBER = 1;
  private int dublinAirPollution_;
  /**
   * <code>int32 dublin_air_pollution = 1;</code>
   */
  public int getDublinAirPollution() {
    return dublinAirPollution_;
  }

  public static final int DUBLIN_WATER_POLLUTION_FIELD_NUMBER = 2;
  private int dublinWaterPollution_;
  /**
   * <code>int32 dublin_water_pollution = 2;</code>
   */
  public int getDublinWaterPollution() {
    return dublinWaterPollution_;
  }

  public static final int CORK_AIR_POLLUTION_FIELD_NUMBER = 3;
  private int corkAirPollution_;
  /**
   * <code>int32 cork_air_pollution = 3;</code>
   */
  public int getCorkAirPollution() {
    return corkAirPollution_;
  }

  public static final int CORK_WATER_POLLUTION_FIELD_NUMBER = 4;
  private int corkWaterPollution_;
  /**
   * <code>int32 cork_water_pollution = 4;</code>
   */
  public int getCorkWaterPollution() {
    return corkWaterPollution_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dublinAirPollution_ != 0) {
      output.writeInt32(1, dublinAirPollution_);
    }
    if (dublinWaterPollution_ != 0) {
      output.writeInt32(2, dublinWaterPollution_);
    }
    if (corkAirPollution_ != 0) {
      output.writeInt32(3, corkAirPollution_);
    }
    if (corkWaterPollution_ != 0) {
      output.writeInt32(4, corkWaterPollution_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dublinAirPollution_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, dublinAirPollution_);
    }
    if (dublinWaterPollution_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, dublinWaterPollution_);
    }
    if (corkAirPollution_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, corkAirPollution_);
    }
    if (corkWaterPollution_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, corkWaterPollution_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.pollutionData.GetReadingsResponse)) {
      return super.equals(obj);
    }
    ca.pollutionData.GetReadingsResponse other = (ca.pollutionData.GetReadingsResponse) obj;

    boolean result = true;
    result = result && (getDublinAirPollution()
        == other.getDublinAirPollution());
    result = result && (getDublinWaterPollution()
        == other.getDublinWaterPollution());
    result = result && (getCorkAirPollution()
        == other.getCorkAirPollution());
    result = result && (getCorkWaterPollution()
        == other.getCorkWaterPollution());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DUBLIN_AIR_POLLUTION_FIELD_NUMBER;
    hash = (53 * hash) + getDublinAirPollution();
    hash = (37 * hash) + DUBLIN_WATER_POLLUTION_FIELD_NUMBER;
    hash = (53 * hash) + getDublinWaterPollution();
    hash = (37 * hash) + CORK_AIR_POLLUTION_FIELD_NUMBER;
    hash = (53 * hash) + getCorkAirPollution();
    hash = (37 * hash) + CORK_WATER_POLLUTION_FIELD_NUMBER;
    hash = (53 * hash) + getCorkWaterPollution();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.pollutionData.GetReadingsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.pollutionData.GetReadingsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.pollutionData.GetReadingsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.pollutionData.GetReadingsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.pollutionData.GetReadingsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.pollutionData.GetReadingsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.pollutionData.GetReadingsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.pollutionData.GetReadingsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.pollutionData.GetReadingsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.pollutionData.GetReadingsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.pollutionData.GetReadingsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.pollutionData.GetReadingsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.pollutionData.GetReadingsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pollutionData.GetReadingsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pollutionData.GetReadingsResponse)
      ca.pollutionData.GetReadingsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.pollutionData.PollutionDataProto.internal_static_pollutionData_GetReadingsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.pollutionData.PollutionDataProto.internal_static_pollutionData_GetReadingsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.pollutionData.GetReadingsResponse.class, ca.pollutionData.GetReadingsResponse.Builder.class);
    }

    // Construct using ca.pollutionData.GetReadingsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      dublinAirPollution_ = 0;

      dublinWaterPollution_ = 0;

      corkAirPollution_ = 0;

      corkWaterPollution_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.pollutionData.PollutionDataProto.internal_static_pollutionData_GetReadingsResponse_descriptor;
    }

    @java.lang.Override
    public ca.pollutionData.GetReadingsResponse getDefaultInstanceForType() {
      return ca.pollutionData.GetReadingsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ca.pollutionData.GetReadingsResponse build() {
      ca.pollutionData.GetReadingsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.pollutionData.GetReadingsResponse buildPartial() {
      ca.pollutionData.GetReadingsResponse result = new ca.pollutionData.GetReadingsResponse(this);
      result.dublinAirPollution_ = dublinAirPollution_;
      result.dublinWaterPollution_ = dublinWaterPollution_;
      result.corkAirPollution_ = corkAirPollution_;
      result.corkWaterPollution_ = corkWaterPollution_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.pollutionData.GetReadingsResponse) {
        return mergeFrom((ca.pollutionData.GetReadingsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.pollutionData.GetReadingsResponse other) {
      if (other == ca.pollutionData.GetReadingsResponse.getDefaultInstance()) return this;
      if (other.getDublinAirPollution() != 0) {
        setDublinAirPollution(other.getDublinAirPollution());
      }
      if (other.getDublinWaterPollution() != 0) {
        setDublinWaterPollution(other.getDublinWaterPollution());
      }
      if (other.getCorkAirPollution() != 0) {
        setCorkAirPollution(other.getCorkAirPollution());
      }
      if (other.getCorkWaterPollution() != 0) {
        setCorkWaterPollution(other.getCorkWaterPollution());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.pollutionData.GetReadingsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.pollutionData.GetReadingsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int dublinAirPollution_ ;
    /**
     * <code>int32 dublin_air_pollution = 1;</code>
     */
    public int getDublinAirPollution() {
      return dublinAirPollution_;
    }
    /**
     * <code>int32 dublin_air_pollution = 1;</code>
     */
    public Builder setDublinAirPollution(int value) {
      
      dublinAirPollution_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 dublin_air_pollution = 1;</code>
     */
    public Builder clearDublinAirPollution() {
      
      dublinAirPollution_ = 0;
      onChanged();
      return this;
    }

    private int dublinWaterPollution_ ;
    /**
     * <code>int32 dublin_water_pollution = 2;</code>
     */
    public int getDublinWaterPollution() {
      return dublinWaterPollution_;
    }
    /**
     * <code>int32 dublin_water_pollution = 2;</code>
     */
    public Builder setDublinWaterPollution(int value) {
      
      dublinWaterPollution_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 dublin_water_pollution = 2;</code>
     */
    public Builder clearDublinWaterPollution() {
      
      dublinWaterPollution_ = 0;
      onChanged();
      return this;
    }

    private int corkAirPollution_ ;
    /**
     * <code>int32 cork_air_pollution = 3;</code>
     */
    public int getCorkAirPollution() {
      return corkAirPollution_;
    }
    /**
     * <code>int32 cork_air_pollution = 3;</code>
     */
    public Builder setCorkAirPollution(int value) {
      
      corkAirPollution_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 cork_air_pollution = 3;</code>
     */
    public Builder clearCorkAirPollution() {
      
      corkAirPollution_ = 0;
      onChanged();
      return this;
    }

    private int corkWaterPollution_ ;
    /**
     * <code>int32 cork_water_pollution = 4;</code>
     */
    public int getCorkWaterPollution() {
      return corkWaterPollution_;
    }
    /**
     * <code>int32 cork_water_pollution = 4;</code>
     */
    public Builder setCorkWaterPollution(int value) {
      
      corkWaterPollution_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 cork_water_pollution = 4;</code>
     */
    public Builder clearCorkWaterPollution() {
      
      corkWaterPollution_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pollutionData.GetReadingsResponse)
  }

  // @@protoc_insertion_point(class_scope:pollutionData.GetReadingsResponse)
  private static final ca.pollutionData.GetReadingsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.pollutionData.GetReadingsResponse();
  }

  public static ca.pollutionData.GetReadingsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetReadingsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetReadingsResponse>() {
    @java.lang.Override
    public GetReadingsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetReadingsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetReadingsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetReadingsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.pollutionData.GetReadingsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

