// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutionData.proto

package ca.pollutionData;

public interface GetReadingsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pollutionData.GetReadingsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string area = 1;</code>
   */
  java.lang.String getArea();
  /**
   * <code>string area = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaBytes();

  /**
   * <code>int32 month = 2;</code>
   */
  int getMonth();
}
