// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutionData.proto

package ca.pollutionData;

/**
 * Protobuf type {@code pollutionData.GetStatisticsResponse}
 */
public  final class GetStatisticsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pollutionData.GetStatisticsResponse)
    GetStatisticsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetStatisticsResponse.newBuilder() to construct.
  private GetStatisticsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetStatisticsResponse() {
    averageAirPollution_ = 0F;
    minimumAirPollution_ = 0F;
    maximumAirPollution_ = 0F;
    averageWaterPollution_ = 0F;
    minimumWaterPollution_ = 0F;
    maximumWaterPollution_ = 0F;
    errorMessage_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetStatisticsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            averageAirPollution_ = input.readFloat();
            break;
          }
          case 21: {

            minimumAirPollution_ = input.readFloat();
            break;
          }
          case 29: {

            maximumAirPollution_ = input.readFloat();
            break;
          }
          case 37: {

            averageWaterPollution_ = input.readFloat();
            break;
          }
          case 45: {

            minimumWaterPollution_ = input.readFloat();
            break;
          }
          case 53: {

            maximumWaterPollution_ = input.readFloat();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            errorMessage_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.pollutionData.PollutionDataProto.internal_static_pollutionData_GetStatisticsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.pollutionData.PollutionDataProto.internal_static_pollutionData_GetStatisticsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.pollutionData.GetStatisticsResponse.class, ca.pollutionData.GetStatisticsResponse.Builder.class);
  }

  public static final int AVERAGE_AIR_POLLUTION_FIELD_NUMBER = 1;
  private float averageAirPollution_;
  /**
   * <code>float average_air_pollution = 1;</code>
   */
  public float getAverageAirPollution() {
    return averageAirPollution_;
  }

  public static final int MINIMUM_AIR_POLLUTION_FIELD_NUMBER = 2;
  private float minimumAirPollution_;
  /**
   * <code>float minimum_air_pollution = 2;</code>
   */
  public float getMinimumAirPollution() {
    return minimumAirPollution_;
  }

  public static final int MAXIMUM_AIR_POLLUTION_FIELD_NUMBER = 3;
  private float maximumAirPollution_;
  /**
   * <code>float maximum_air_pollution = 3;</code>
   */
  public float getMaximumAirPollution() {
    return maximumAirPollution_;
  }

  public static final int AVERAGE_WATER_POLLUTION_FIELD_NUMBER = 4;
  private float averageWaterPollution_;
  /**
   * <code>float average_water_pollution = 4;</code>
   */
  public float getAverageWaterPollution() {
    return averageWaterPollution_;
  }

  public static final int MINIMUM_WATER_POLLUTION_FIELD_NUMBER = 5;
  private float minimumWaterPollution_;
  /**
   * <code>float minimum_water_pollution = 5;</code>
   */
  public float getMinimumWaterPollution() {
    return minimumWaterPollution_;
  }

  public static final int MAXIMUM_WATER_POLLUTION_FIELD_NUMBER = 6;
  private float maximumWaterPollution_;
  /**
   * <code>float maximum_water_pollution = 6;</code>
   */
  public float getMaximumWaterPollution() {
    return maximumWaterPollution_;
  }

  public static final int ERROR_MESSAGE_FIELD_NUMBER = 7;
  private volatile java.lang.Object errorMessage_;
  /**
   * <code>string error_message = 7;</code>
   */
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string error_message = 7;</code>
   */
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (averageAirPollution_ != 0F) {
      output.writeFloat(1, averageAirPollution_);
    }
    if (minimumAirPollution_ != 0F) {
      output.writeFloat(2, minimumAirPollution_);
    }
    if (maximumAirPollution_ != 0F) {
      output.writeFloat(3, maximumAirPollution_);
    }
    if (averageWaterPollution_ != 0F) {
      output.writeFloat(4, averageWaterPollution_);
    }
    if (minimumWaterPollution_ != 0F) {
      output.writeFloat(5, minimumWaterPollution_);
    }
    if (maximumWaterPollution_ != 0F) {
      output.writeFloat(6, maximumWaterPollution_);
    }
    if (!getErrorMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, errorMessage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (averageAirPollution_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, averageAirPollution_);
    }
    if (minimumAirPollution_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, minimumAirPollution_);
    }
    if (maximumAirPollution_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, maximumAirPollution_);
    }
    if (averageWaterPollution_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, averageWaterPollution_);
    }
    if (minimumWaterPollution_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(5, minimumWaterPollution_);
    }
    if (maximumWaterPollution_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(6, maximumWaterPollution_);
    }
    if (!getErrorMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, errorMessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.pollutionData.GetStatisticsResponse)) {
      return super.equals(obj);
    }
    ca.pollutionData.GetStatisticsResponse other = (ca.pollutionData.GetStatisticsResponse) obj;

    boolean result = true;
    result = result && (
        java.lang.Float.floatToIntBits(getAverageAirPollution())
        == java.lang.Float.floatToIntBits(
            other.getAverageAirPollution()));
    result = result && (
        java.lang.Float.floatToIntBits(getMinimumAirPollution())
        == java.lang.Float.floatToIntBits(
            other.getMinimumAirPollution()));
    result = result && (
        java.lang.Float.floatToIntBits(getMaximumAirPollution())
        == java.lang.Float.floatToIntBits(
            other.getMaximumAirPollution()));
    result = result && (
        java.lang.Float.floatToIntBits(getAverageWaterPollution())
        == java.lang.Float.floatToIntBits(
            other.getAverageWaterPollution()));
    result = result && (
        java.lang.Float.floatToIntBits(getMinimumWaterPollution())
        == java.lang.Float.floatToIntBits(
            other.getMinimumWaterPollution()));
    result = result && (
        java.lang.Float.floatToIntBits(getMaximumWaterPollution())
        == java.lang.Float.floatToIntBits(
            other.getMaximumWaterPollution()));
    result = result && getErrorMessage()
        .equals(other.getErrorMessage());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AVERAGE_AIR_POLLUTION_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getAverageAirPollution());
    hash = (37 * hash) + MINIMUM_AIR_POLLUTION_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getMinimumAirPollution());
    hash = (37 * hash) + MAXIMUM_AIR_POLLUTION_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getMaximumAirPollution());
    hash = (37 * hash) + AVERAGE_WATER_POLLUTION_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getAverageWaterPollution());
    hash = (37 * hash) + MINIMUM_WATER_POLLUTION_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getMinimumWaterPollution());
    hash = (37 * hash) + MAXIMUM_WATER_POLLUTION_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getMaximumWaterPollution());
    hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.pollutionData.GetStatisticsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.pollutionData.GetStatisticsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.pollutionData.GetStatisticsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.pollutionData.GetStatisticsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.pollutionData.GetStatisticsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.pollutionData.GetStatisticsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.pollutionData.GetStatisticsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.pollutionData.GetStatisticsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.pollutionData.GetStatisticsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.pollutionData.GetStatisticsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.pollutionData.GetStatisticsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.pollutionData.GetStatisticsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.pollutionData.GetStatisticsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pollutionData.GetStatisticsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pollutionData.GetStatisticsResponse)
      ca.pollutionData.GetStatisticsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.pollutionData.PollutionDataProto.internal_static_pollutionData_GetStatisticsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.pollutionData.PollutionDataProto.internal_static_pollutionData_GetStatisticsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.pollutionData.GetStatisticsResponse.class, ca.pollutionData.GetStatisticsResponse.Builder.class);
    }

    // Construct using ca.pollutionData.GetStatisticsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      averageAirPollution_ = 0F;

      minimumAirPollution_ = 0F;

      maximumAirPollution_ = 0F;

      averageWaterPollution_ = 0F;

      minimumWaterPollution_ = 0F;

      maximumWaterPollution_ = 0F;

      errorMessage_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.pollutionData.PollutionDataProto.internal_static_pollutionData_GetStatisticsResponse_descriptor;
    }

    @java.lang.Override
    public ca.pollutionData.GetStatisticsResponse getDefaultInstanceForType() {
      return ca.pollutionData.GetStatisticsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ca.pollutionData.GetStatisticsResponse build() {
      ca.pollutionData.GetStatisticsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.pollutionData.GetStatisticsResponse buildPartial() {
      ca.pollutionData.GetStatisticsResponse result = new ca.pollutionData.GetStatisticsResponse(this);
      result.averageAirPollution_ = averageAirPollution_;
      result.minimumAirPollution_ = minimumAirPollution_;
      result.maximumAirPollution_ = maximumAirPollution_;
      result.averageWaterPollution_ = averageWaterPollution_;
      result.minimumWaterPollution_ = minimumWaterPollution_;
      result.maximumWaterPollution_ = maximumWaterPollution_;
      result.errorMessage_ = errorMessage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.pollutionData.GetStatisticsResponse) {
        return mergeFrom((ca.pollutionData.GetStatisticsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.pollutionData.GetStatisticsResponse other) {
      if (other == ca.pollutionData.GetStatisticsResponse.getDefaultInstance()) return this;
      if (other.getAverageAirPollution() != 0F) {
        setAverageAirPollution(other.getAverageAirPollution());
      }
      if (other.getMinimumAirPollution() != 0F) {
        setMinimumAirPollution(other.getMinimumAirPollution());
      }
      if (other.getMaximumAirPollution() != 0F) {
        setMaximumAirPollution(other.getMaximumAirPollution());
      }
      if (other.getAverageWaterPollution() != 0F) {
        setAverageWaterPollution(other.getAverageWaterPollution());
      }
      if (other.getMinimumWaterPollution() != 0F) {
        setMinimumWaterPollution(other.getMinimumWaterPollution());
      }
      if (other.getMaximumWaterPollution() != 0F) {
        setMaximumWaterPollution(other.getMaximumWaterPollution());
      }
      if (!other.getErrorMessage().isEmpty()) {
        errorMessage_ = other.errorMessage_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.pollutionData.GetStatisticsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.pollutionData.GetStatisticsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float averageAirPollution_ ;
    /**
     * <code>float average_air_pollution = 1;</code>
     */
    public float getAverageAirPollution() {
      return averageAirPollution_;
    }
    /**
     * <code>float average_air_pollution = 1;</code>
     */
    public Builder setAverageAirPollution(float value) {
      
      averageAirPollution_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float average_air_pollution = 1;</code>
     */
    public Builder clearAverageAirPollution() {
      
      averageAirPollution_ = 0F;
      onChanged();
      return this;
    }

    private float minimumAirPollution_ ;
    /**
     * <code>float minimum_air_pollution = 2;</code>
     */
    public float getMinimumAirPollution() {
      return minimumAirPollution_;
    }
    /**
     * <code>float minimum_air_pollution = 2;</code>
     */
    public Builder setMinimumAirPollution(float value) {
      
      minimumAirPollution_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float minimum_air_pollution = 2;</code>
     */
    public Builder clearMinimumAirPollution() {
      
      minimumAirPollution_ = 0F;
      onChanged();
      return this;
    }

    private float maximumAirPollution_ ;
    /**
     * <code>float maximum_air_pollution = 3;</code>
     */
    public float getMaximumAirPollution() {
      return maximumAirPollution_;
    }
    /**
     * <code>float maximum_air_pollution = 3;</code>
     */
    public Builder setMaximumAirPollution(float value) {
      
      maximumAirPollution_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float maximum_air_pollution = 3;</code>
     */
    public Builder clearMaximumAirPollution() {
      
      maximumAirPollution_ = 0F;
      onChanged();
      return this;
    }

    private float averageWaterPollution_ ;
    /**
     * <code>float average_water_pollution = 4;</code>
     */
    public float getAverageWaterPollution() {
      return averageWaterPollution_;
    }
    /**
     * <code>float average_water_pollution = 4;</code>
     */
    public Builder setAverageWaterPollution(float value) {
      
      averageWaterPollution_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float average_water_pollution = 4;</code>
     */
    public Builder clearAverageWaterPollution() {
      
      averageWaterPollution_ = 0F;
      onChanged();
      return this;
    }

    private float minimumWaterPollution_ ;
    /**
     * <code>float minimum_water_pollution = 5;</code>
     */
    public float getMinimumWaterPollution() {
      return minimumWaterPollution_;
    }
    /**
     * <code>float minimum_water_pollution = 5;</code>
     */
    public Builder setMinimumWaterPollution(float value) {
      
      minimumWaterPollution_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float minimum_water_pollution = 5;</code>
     */
    public Builder clearMinimumWaterPollution() {
      
      minimumWaterPollution_ = 0F;
      onChanged();
      return this;
    }

    private float maximumWaterPollution_ ;
    /**
     * <code>float maximum_water_pollution = 6;</code>
     */
    public float getMaximumWaterPollution() {
      return maximumWaterPollution_;
    }
    /**
     * <code>float maximum_water_pollution = 6;</code>
     */
    public Builder setMaximumWaterPollution(float value) {
      
      maximumWaterPollution_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float maximum_water_pollution = 6;</code>
     */
    public Builder clearMaximumWaterPollution() {
      
      maximumWaterPollution_ = 0F;
      onChanged();
      return this;
    }

    private java.lang.Object errorMessage_ = "";
    /**
     * <code>string error_message = 7;</code>
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string error_message = 7;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string error_message = 7;</code>
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errorMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string error_message = 7;</code>
     */
    public Builder clearErrorMessage() {
      
      errorMessage_ = getDefaultInstance().getErrorMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string error_message = 7;</code>
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errorMessage_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pollutionData.GetStatisticsResponse)
  }

  // @@protoc_insertion_point(class_scope:pollutionData.GetStatisticsResponse)
  private static final ca.pollutionData.GetStatisticsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.pollutionData.GetStatisticsResponse();
  }

  public static ca.pollutionData.GetStatisticsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetStatisticsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetStatisticsResponse>() {
    @java.lang.Override
    public GetStatisticsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetStatisticsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetStatisticsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetStatisticsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.pollutionData.GetStatisticsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

