// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userAuthentication.proto

package ca.userAuthentication;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ca.userAuthentication.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ca.userAuthentication.LoginStatus status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.ca.userAuthentication.LoginStatus status = 1;</code>
   */
  ca.userAuthentication.LoginStatus getStatus();

  /**
   * <code>string userStatus = 2;</code>
   */
  java.lang.String getUserStatus();
  /**
   * <code>string userStatus = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserStatusBytes();
}
