// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userAuthentication.proto

package ca.userAuthentication;

public interface LogoutResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ca.userAuthentication.LogoutResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ca.userAuthentication.LogoutStatus status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.ca.userAuthentication.LogoutStatus status = 1;</code>
   */
  ca.userAuthentication.LogoutStatus getStatus();
}
