// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userAuthentication.proto

package ca.userAuthentication;

public interface LogoutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ca.userAuthentication.LogoutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userStatus = 1;</code>
   */
  java.lang.String getUserStatus();
  /**
   * <code>string userStatus = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserStatusBytes();
}
