// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userAuthentication.proto

package ca.userAuthentication;

public interface RequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ca.userAuthentication.RequestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
