// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userAuthentication.proto

package ca.userAuthentication;

public final class userAuthenticationProto {
  private userAuthenticationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_userAuthentication_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ca_userAuthentication_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_userAuthentication_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ca_userAuthentication_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_userAuthentication_LogoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ca_userAuthentication_LogoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_userAuthentication_LogoutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ca_userAuthentication_LogoutResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_userAuthentication_RequestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ca_userAuthentication_RequestMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_userAuthentication_ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ca_userAuthentication_ResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030userAuthentication.proto\022\025ca.userAuthe" +
      "ntication\"/\n\014LoginRequest\022\r\n\005email\030\001 \001(\t" +
      "\022\020\n\010password\030\002 \001(\t\"W\n\rLoginResponse\0222\n\006s" +
      "tatus\030\001 \001(\0162\".ca.userAuthentication.Logi" +
      "nStatus\022\022\n\nuserStatus\030\002 \001(\t\"#\n\rLogoutReq" +
      "uest\022\022\n\nuserStatus\030\001 \001(\t\"E\n\016LogoutRespon" +
      "se\0223\n\006status\030\001 \001(\0162#.ca.userAuthenticati" +
      "on.LogoutStatus\"0\n\016RequestMessage\022\014\n\004tex" +
      "t\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"!\n\017ResponseMes" +
      "sage\022\016\n\006length\030\001 \001(\005*D\n\013LoginStatus\022\032\n\026L" +
      "OGGED_IN_SUCCESSFULLY\020\000\022\031\n\025INCORRECT_CRE" +
      "DENTIALS\020\001*C\n\014LogoutStatus\022\033\n\027LOGGED_OUT" +
      "_SUCCESSFULLY\020\000\022\026\n\022INVALID_USERSTATUS\020\0012" +
      "\254\002\n\022userAuthentication\022T\n\005Login\022#.ca.use" +
      "rAuthentication.LoginRequest\032$.ca.userAu" +
      "thentication.LoginResponse\"\000\022W\n\006Logout\022$" +
      ".ca.userAuthentication.LogoutRequest\032%.c" +
      "a.userAuthentication.LogoutResponse\"\000\022g\n" +
      "\024userAuthenticationDo\022%.ca.userAuthentic" +
      "ation.RequestMessage\032&.ca.userAuthentica" +
      "tion.ResponseMessage\"\000B2\n\025ca.userAuthent" +
      "icationB\027userAuthenticationProtoP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ca_userAuthentication_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ca_userAuthentication_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ca_userAuthentication_LoginRequest_descriptor,
        new java.lang.String[] { "Email", "Password", });
    internal_static_ca_userAuthentication_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ca_userAuthentication_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ca_userAuthentication_LoginResponse_descriptor,
        new java.lang.String[] { "Status", "UserStatus", });
    internal_static_ca_userAuthentication_LogoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ca_userAuthentication_LogoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ca_userAuthentication_LogoutRequest_descriptor,
        new java.lang.String[] { "UserStatus", });
    internal_static_ca_userAuthentication_LogoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ca_userAuthentication_LogoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ca_userAuthentication_LogoutResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_ca_userAuthentication_RequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ca_userAuthentication_RequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ca_userAuthentication_RequestMessage_descriptor,
        new java.lang.String[] { "Text", "Password", });
    internal_static_ca_userAuthentication_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ca_userAuthentication_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ca_userAuthentication_ResponseMessage_descriptor,
        new java.lang.String[] { "Length", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
