// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Notification.proto

package ca.notification;

public final class NotificationProto {
  private NotificationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_userAuthentication_SubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ca_userAuthentication_SubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_userAuthentication_SubscriptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ca_userAuthentication_SubscriptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_userAuthentication_NotificationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ca_userAuthentication_NotificationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_userAuthentication_NotificationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ca_userAuthentication_NotificationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_userAuthentication_RequestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ca_userAuthentication_RequestMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_userAuthentication_ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ca_userAuthentication_ResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Notification.proto\022\025ca.userAuthenticat" +
      "ion\"0\n\023SubscriptionRequest\022\031\n\021subscripti" +
      "onEmail\030\001 \001(\t\"8\n\024SubscriptionResponse\022 \n" +
      "\030subscriptionConfirmation\030\001 \001(\t\"0\n\023Notif" +
      "icationRequest\022\031\n\021notificationEmail\030\001 \001(" +
      "\t\"}\n\024NotificationResponse\022\031\n\021notificatio" +
      "nEmail\030\001 \001(\t\022 \n\030notificationConfirmation" +
      "\030\002 \001(\t\022\016\n\006status\030\003 \001(\t\022\030\n\020numNotificatio" +
      "ns\030\004 \001(\005\"0\n\016RequestMessage\022\014\n\004text\030\001 \001(\t" +
      "\022\020\n\010password\030\002 \001(\t\"!\n\017ResponseMessage\022\016\n" +
      "\006length\030\001 \001(\0052\301\002\n\014Notification\022i\n\014Subscr" +
      "iption\022*.ca.userAuthentication.Subscript" +
      "ionRequest\032+.ca.userAuthentication.Subsc" +
      "riptionResponse\"\000\022c\n\006Notify\022*.ca.userAut" +
      "hentication.NotificationRequest\032+.ca.use" +
      "rAuthentication.NotificationResponse\"\000\022a" +
      "\n\016DoNotification\022%.ca.userAuthentication" +
      ".RequestMessage\032&.ca.userAuthentication." +
      "ResponseMessage\"\000B&\n\017ca.notificationB\021No" +
      "tificationProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ca_userAuthentication_SubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ca_userAuthentication_SubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ca_userAuthentication_SubscriptionRequest_descriptor,
        new java.lang.String[] { "SubscriptionEmail", });
    internal_static_ca_userAuthentication_SubscriptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ca_userAuthentication_SubscriptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ca_userAuthentication_SubscriptionResponse_descriptor,
        new java.lang.String[] { "SubscriptionConfirmation", });
    internal_static_ca_userAuthentication_NotificationRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ca_userAuthentication_NotificationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ca_userAuthentication_NotificationRequest_descriptor,
        new java.lang.String[] { "NotificationEmail", });
    internal_static_ca_userAuthentication_NotificationResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ca_userAuthentication_NotificationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ca_userAuthentication_NotificationResponse_descriptor,
        new java.lang.String[] { "NotificationEmail", "NotificationConfirmation", "Status", "NumNotifications", });
    internal_static_ca_userAuthentication_RequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ca_userAuthentication_RequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ca_userAuthentication_RequestMessage_descriptor,
        new java.lang.String[] { "Text", "Password", });
    internal_static_ca_userAuthentication_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ca_userAuthentication_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ca_userAuthentication_ResponseMessage_descriptor,
        new java.lang.String[] { "Length", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
