// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Notification.proto

package ca.notification;

public interface NotificationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ca.userAuthentication.NotificationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string notificationEmail = 1;</code>
   */
  java.lang.String getNotificationEmail();
  /**
   * <code>string notificationEmail = 1;</code>
   */
  com.google.protobuf.ByteString
      getNotificationEmailBytes();

  /**
   * <code>string notificationConfirmation = 2;</code>
   */
  java.lang.String getNotificationConfirmation();
  /**
   * <code>string notificationConfirmation = 2;</code>
   */
  com.google.protobuf.ByteString
      getNotificationConfirmationBytes();

  /**
   * <code>string status = 3;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 3;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 number_of_notifications = 4;</code>
   */
  int getNumberOfNotifications();
}
