// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Notification.proto

package ca.notification;

/**
 * Protobuf type {@code ca.userAuthentication.NotificationResponse}
 */
public  final class NotificationResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ca.userAuthentication.NotificationResponse)
    NotificationResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NotificationResponse.newBuilder() to construct.
  private NotificationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NotificationResponse() {
    notificationEmail_ = "";
    notificationConfirmation_ = "";
    status_ = "";
    numNotifications_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NotificationResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            notificationEmail_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            notificationConfirmation_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            status_ = s;
            break;
          }
          case 32: {

            numNotifications_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.notification.NotificationProto.internal_static_ca_userAuthentication_NotificationResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.notification.NotificationProto.internal_static_ca_userAuthentication_NotificationResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.notification.NotificationResponse.class, ca.notification.NotificationResponse.Builder.class);
  }

  public static final int NOTIFICATIONEMAIL_FIELD_NUMBER = 1;
  private volatile java.lang.Object notificationEmail_;
  /**
   * <code>string notificationEmail = 1;</code>
   */
  public java.lang.String getNotificationEmail() {
    java.lang.Object ref = notificationEmail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      notificationEmail_ = s;
      return s;
    }
  }
  /**
   * <code>string notificationEmail = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNotificationEmailBytes() {
    java.lang.Object ref = notificationEmail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      notificationEmail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOTIFICATIONCONFIRMATION_FIELD_NUMBER = 2;
  private volatile java.lang.Object notificationConfirmation_;
  /**
   * <code>string notificationConfirmation = 2;</code>
   */
  public java.lang.String getNotificationConfirmation() {
    java.lang.Object ref = notificationConfirmation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      notificationConfirmation_ = s;
      return s;
    }
  }
  /**
   * <code>string notificationConfirmation = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNotificationConfirmationBytes() {
    java.lang.Object ref = notificationConfirmation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      notificationConfirmation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 3;
  private volatile java.lang.Object status_;
  /**
   * <code>string status = 3;</code>
   */
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 3;</code>
   */
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUMNOTIFICATIONS_FIELD_NUMBER = 4;
  private int numNotifications_;
  /**
   * <code>int32 numNotifications = 4;</code>
   */
  public int getNumNotifications() {
    return numNotifications_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNotificationEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, notificationEmail_);
    }
    if (!getNotificationConfirmationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, notificationConfirmation_);
    }
    if (!getStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, status_);
    }
    if (numNotifications_ != 0) {
      output.writeInt32(4, numNotifications_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNotificationEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, notificationEmail_);
    }
    if (!getNotificationConfirmationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, notificationConfirmation_);
    }
    if (!getStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, status_);
    }
    if (numNotifications_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, numNotifications_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.notification.NotificationResponse)) {
      return super.equals(obj);
    }
    ca.notification.NotificationResponse other = (ca.notification.NotificationResponse) obj;

    boolean result = true;
    result = result && getNotificationEmail()
        .equals(other.getNotificationEmail());
    result = result && getNotificationConfirmation()
        .equals(other.getNotificationConfirmation());
    result = result && getStatus()
        .equals(other.getStatus());
    result = result && (getNumNotifications()
        == other.getNumNotifications());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NOTIFICATIONEMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getNotificationEmail().hashCode();
    hash = (37 * hash) + NOTIFICATIONCONFIRMATION_FIELD_NUMBER;
    hash = (53 * hash) + getNotificationConfirmation().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + NUMNOTIFICATIONS_FIELD_NUMBER;
    hash = (53 * hash) + getNumNotifications();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.notification.NotificationResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.notification.NotificationResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.notification.NotificationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.notification.NotificationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.notification.NotificationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.notification.NotificationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.notification.NotificationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.notification.NotificationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.notification.NotificationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.notification.NotificationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.notification.NotificationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.notification.NotificationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.notification.NotificationResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ca.userAuthentication.NotificationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ca.userAuthentication.NotificationResponse)
      ca.notification.NotificationResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.notification.NotificationProto.internal_static_ca_userAuthentication_NotificationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.notification.NotificationProto.internal_static_ca_userAuthentication_NotificationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.notification.NotificationResponse.class, ca.notification.NotificationResponse.Builder.class);
    }

    // Construct using ca.notification.NotificationResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      notificationEmail_ = "";

      notificationConfirmation_ = "";

      status_ = "";

      numNotifications_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.notification.NotificationProto.internal_static_ca_userAuthentication_NotificationResponse_descriptor;
    }

    @java.lang.Override
    public ca.notification.NotificationResponse getDefaultInstanceForType() {
      return ca.notification.NotificationResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ca.notification.NotificationResponse build() {
      ca.notification.NotificationResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.notification.NotificationResponse buildPartial() {
      ca.notification.NotificationResponse result = new ca.notification.NotificationResponse(this);
      result.notificationEmail_ = notificationEmail_;
      result.notificationConfirmation_ = notificationConfirmation_;
      result.status_ = status_;
      result.numNotifications_ = numNotifications_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.notification.NotificationResponse) {
        return mergeFrom((ca.notification.NotificationResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.notification.NotificationResponse other) {
      if (other == ca.notification.NotificationResponse.getDefaultInstance()) return this;
      if (!other.getNotificationEmail().isEmpty()) {
        notificationEmail_ = other.notificationEmail_;
        onChanged();
      }
      if (!other.getNotificationConfirmation().isEmpty()) {
        notificationConfirmation_ = other.notificationConfirmation_;
        onChanged();
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        onChanged();
      }
      if (other.getNumNotifications() != 0) {
        setNumNotifications(other.getNumNotifications());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.notification.NotificationResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.notification.NotificationResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object notificationEmail_ = "";
    /**
     * <code>string notificationEmail = 1;</code>
     */
    public java.lang.String getNotificationEmail() {
      java.lang.Object ref = notificationEmail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        notificationEmail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string notificationEmail = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNotificationEmailBytes() {
      java.lang.Object ref = notificationEmail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        notificationEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string notificationEmail = 1;</code>
     */
    public Builder setNotificationEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      notificationEmail_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string notificationEmail = 1;</code>
     */
    public Builder clearNotificationEmail() {
      
      notificationEmail_ = getDefaultInstance().getNotificationEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string notificationEmail = 1;</code>
     */
    public Builder setNotificationEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      notificationEmail_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object notificationConfirmation_ = "";
    /**
     * <code>string notificationConfirmation = 2;</code>
     */
    public java.lang.String getNotificationConfirmation() {
      java.lang.Object ref = notificationConfirmation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        notificationConfirmation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string notificationConfirmation = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNotificationConfirmationBytes() {
      java.lang.Object ref = notificationConfirmation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        notificationConfirmation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string notificationConfirmation = 2;</code>
     */
    public Builder setNotificationConfirmation(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      notificationConfirmation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string notificationConfirmation = 2;</code>
     */
    public Builder clearNotificationConfirmation() {
      
      notificationConfirmation_ = getDefaultInstance().getNotificationConfirmation();
      onChanged();
      return this;
    }
    /**
     * <code>string notificationConfirmation = 2;</code>
     */
    public Builder setNotificationConfirmationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      notificationConfirmation_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 3;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 3;</code>
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 3;</code>
     */
    public Builder clearStatus() {
      
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string status = 3;</code>
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      status_ = value;
      onChanged();
      return this;
    }

    private int numNotifications_ ;
    /**
     * <code>int32 numNotifications = 4;</code>
     */
    public int getNumNotifications() {
      return numNotifications_;
    }
    /**
     * <code>int32 numNotifications = 4;</code>
     */
    public Builder setNumNotifications(int value) {
      
      numNotifications_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 numNotifications = 4;</code>
     */
    public Builder clearNumNotifications() {
      
      numNotifications_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ca.userAuthentication.NotificationResponse)
  }

  // @@protoc_insertion_point(class_scope:ca.userAuthentication.NotificationResponse)
  private static final ca.notification.NotificationResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.notification.NotificationResponse();
  }

  public static ca.notification.NotificationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NotificationResponse>
      PARSER = new com.google.protobuf.AbstractParser<NotificationResponse>() {
    @java.lang.Override
    public NotificationResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NotificationResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NotificationResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NotificationResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.notification.NotificationResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

