// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Notification.proto

package ca.notification;

public interface NotificationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ca.userAuthentication.NotificationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string notificationEmail = 1;</code>
   */
  java.lang.String getNotificationEmail();
  /**
   * <code>string notificationEmail = 1;</code>
   */
  com.google.protobuf.ByteString
      getNotificationEmailBytes();
}
