// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Notification.proto

package ca.notification;

public interface ResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ca.userAuthentication.ResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 length = 1;</code>
   */
  int getLength();
}
