// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Notification.proto

package ca.notification;

public interface SubscriptionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ca.userAuthentication.SubscriptionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string subscriptionConfirmation = 1;</code>
   */
  java.lang.String getSubscriptionConfirmation();
  /**
   * <code>string subscriptionConfirmation = 1;</code>
   */
  com.google.protobuf.ByteString
      getSubscriptionConfirmationBytes();
}
