// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Notification.proto

package ca.notification;

public interface SubscriptionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ca.userAuthentication.SubscriptionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string subscriptionEmail = 1;</code>
   */
  java.lang.String getSubscriptionEmail();
  /**
   * <code>string subscriptionEmail = 1;</code>
   */
  com.google.protobuf.ByteString
      getSubscriptionEmailBytes();
}
